# Generated by Django 5.1 on 2024-09-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_security_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
