# Generated by Django 5.1 on 2024-09-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default='default item', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='item_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(default='default_type', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='received_date',
            field=models.DateField(default='2023-09-01'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='terpenes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thc_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
