# Generated by Django 5.1.15 on 2026-09-06 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_price_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('flower', 'Flower'), ('edible', 'Edible'), ('concentrate', 'Concentrate'), ('topical', 'Topical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='received_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
