# Generated by Django 5.1 on 2024-08-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('prescription_details', models.TextField()),
                ('medical_card_id', models.CharField(max_length=255, unique=True)),
                ('medical_card_expiration', models.DateField()),
            ],
        ),
    ]
